// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktfrtxmquxxlpgxqsfel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0ZnJ0eG1xdXh4bHBneHFzZmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDQ3MzYsImV4cCI6MjA3MjM4MDczNn0.c1wTY27Zn-DlEU1WdKE3LIhq8iQ6kjI5wYh16vaoEr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});